#!/usr/bin/env bash

if
  [[ -s "/home/quirky30/.rvm/gems/ruby-2.3.3/environment" ]]
then
  source "/home/quirky30/.rvm/gems/ruby-2.3.3/environment"
  exec sass "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/quirky30/.rvm/gems/ruby-2.3.3/environment'" >&2
  exit 1
fi
